"""
AI Agents Prompts Module
Contains all prompts used by the various AI agents
"""

from .system_design_prompts import (
    SYSTEM_DESIGN_TOPICS,
    OPENING_QUESTION_PROMPTS,
    EVALUATION_PROMPTS,
    FEEDBACK_PROMPTS,
    DIFFICULTY_ADJUSTMENT_PROMPTS,
    QUESTION_TYPE_TEMPLATES,
    CONTEXT_ANALYSIS_PROMPTS,
)

from .evaluation_prompts import (
    EVALUATION_SYSTEM_PROMPTS,
    TOPIC_EVALUATION_GUIDELINES,
    SCORING_RUBRICS,
)

from .question_generation_prompts import (
    QUESTION_GENERATION_SYSTEM_PROMPTS,
    QUESTION_TYPE_PROMPTS,
    TOPIC_QUESTION_TEMPLATES,
    PROGRESSIVE_STRATEGIES,
    HINT_TEMPLATES,
)

from .orchestrator_prompts import (
    ORCHESTRATOR_SYSTEM_PROMPTS,
    ACTION_DETERMINATION_PROMPTS,
    INTERVIEW_PHASES,
    ACTION_PRIORITY_MATRIX,
    CONTEXT_WEIGHTS,
)

__all__ = [
    # System Design Prompts
    "SYSTEM_DESIGN_TOPICS",
    "OPENING_QUESTION_PROMPTS",
    "EVALUATION_PROMPTS",
    "FEEDBACK_PROMPTS",
    "DIFFICULTY_ADJUSTMENT_PROMPTS",
    "QUESTION_TYPE_TEMPLATES",
    "CONTEXT_ANALYSIS_PROMPTS",
    # Evaluation Prompts
    "EVALUATION_SYSTEM_PROMPTS",
    "TOPIC_EVALUATION_GUIDELINES",
    "SCORING_RUBRICS",
    # Question Generation Prompts
    "QUESTION_GENERATION_SYSTEM_PROMPTS",
    "QUESTION_TYPE_PROMPTS",
    "TOPIC_QUESTION_TEMPLATES",
    "PROGRESSIVE_STRATEGIES",
    "HINT_TEMPLATES",
    # Orchestrator Prompts
    "ORCHESTRATOR_SYSTEM_PROMPTS",
    "ACTION_DETERMINATION_PROMPTS",
    "INTERVIEW_PHASES",
    "ACTION_PRIORITY_MATRIX",
    "CONTEXT_WEIGHTS",
]
