"""
AI Agents Prompts Module
Contains system design prompts for memory-enhanced architecture
"""

from .system_design_prompts import (
    SYSTEM_DESIGN_TOPICS,
    OPENING_QUESTION_PROMPTS,
    EVALUATION_PROMPTS,
    FEEDBACK_PROMPTS,
    DIFFICULTY_ADJUSTMENT_PROMPTS,
    QUESTION_TYPE_TEMPLATES,
    CONTEXT_ANALYSIS_PROMPTS,
)

from .specialized_agent_prompts import (
    # Question Generator Prompts
    QUESTION_GENERATOR_SYSTEM_PROMPT,
    OPENING_QUESTION_PROMPT_TEMPLATE,
    FOLLOW_UP_QUESTION_PROMPT_TEMPLATE,
    STREAMING_FOLLOW_UP_PROMPT_TEMPLATE,
    # Answer Evaluator Prompts
    ANSWER_EVALUATOR_SYSTEM_PROMPT,
    ANSWER_EVALUATION_PROMPT_TEMPLATE,
    # Feedback Provider Prompts
    FEEDBACK_PROVIDER_SYSTEM_PROMPT,
    FEEDBACK_PROVIDER_FEEDBACK_TEMPLATE,
    PERFORMANCE_ANALYZER_TOOL_PROMPT_TEMPLATE,
    RECOMMENDATION_GENERATOR_TOOL_PROMPT_TEMPLATE,
    # Summary Generator Prompts
    SUMMARY_GENERATOR_SYSTEM_PROMPT,
    SUMMARY_GENERATOR_SUMMARY_TEMPLATE,
    INTERVIEW_SUMMARY_PROMPT_TEMPLATE,
)

__all__ = [
    # System Design Prompts (Core prompts still used for reference)
    "SYSTEM_DESIGN_TOPICS",
    "OPENING_QUESTION_PROMPTS",
    "EVALUATION_PROMPTS",
    "FEEDBACK_PROMPTS",
    "DIFFICULTY_ADJUSTMENT_PROMPTS",
    "QUESTION_TYPE_TEMPLATES",
    "CONTEXT_ANALYSIS_PROMPTS",
    # Specialized Agent Prompts (Memory-Enhanced)
    "QUESTION_GENERATOR_SYSTEM_PROMPT",
    "OPENING_QUESTION_PROMPT_TEMPLATE",
    "FOLLOW_UP_QUESTION_PROMPT_TEMPLATE",
    "STREAMING_FOLLOW_UP_PROMPT_TEMPLATE",
    "ANSWER_EVALUATOR_SYSTEM_PROMPT",
    "ANSWER_EVALUATION_PROMPT_TEMPLATE",
    "FEEDBACK_PROVIDER_SYSTEM_PROMPT",
    "FEEDBACK_PROVIDER_FEEDBACK_TEMPLATE",
    "PERFORMANCE_ANALYZER_TOOL_PROMPT_TEMPLATE",
    "RECOMMENDATION_GENERATOR_TOOL_PROMPT_TEMPLATE",
    "SUMMARY_GENERATOR_SYSTEM_PROMPT",
    "SUMMARY_GENERATOR_SUMMARY_TEMPLATE",
    "INTERVIEW_SUMMARY_PROMPT_TEMPLATE",
]
